
trigger:
- main
- release/*

resources:
- repo: self
variables:
  ${{ if startsWith(variables['Build.SourceBranchName'], 'release') }}:
    defaultTag : $[replace(variables['Build.SourceBranch'], 'refs/heads/release/', '')]
  ${{ else }}:
    defaultTag : $(Build.SourceBranchName)
  tag: $[coalesce(variables.releaseVersion, variables.defaultTag)]

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - bash: |
        echo defaultTag: $(defaultTag)
        echo tag: $(tag)
      displayName: Print versions