apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.nodePort }}
      protocol: TCP
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.name }}
    name: {{ .Values.name }}